name: Trigger Main Repository Workflow

on:
  push:
    branches: [main] # adjust if needed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Rebuild in Main Repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_FINE_GRAINED_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/jarooda/jarooda.github.io/dispatches \
            -d '{"event_type": "rebuild"}'
